[build]
builder = "nixpacks"

[build.nixpacksPlan]
providers = ["python"]

[deploy]
startCommand = "celery -A app.worker.celery_worker worker --loglevel=info --concurrency=4"
restartPolicyType = "on_failure"
