name: Python Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.13'

    - name: Install uv
      run: |
        curl -LsSf https://astral.sh/uv/install.sh | sh
        echo "$HOME/.cargo/bin" >> $GITHUB_PATH

    - name: Install dependencies
      run: |
        cd backend
        uv venv
        source .venv/bin/activate
        uv pip install pytest
        if [ -f pyproject.toml ]; then uv pip install -e .; fi
        
    - name: Run tests
      run: |
        cd backend
        source .venv/bin/activate
        python -m pytest app/tests/ -v
        
    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: backend/pytest-results.xml
        if-no-files-found: ignore 